DROP TABLE IF EXISTS account_tbl;
create table account_tbl (id bigint generated by default as identity, account_id bigint not null, account_balance float(53) not null, account_currency varchar(255) not null, client_id bigint, primary key (id));

DROP TABLE IF EXISTS client_tbl;
create table client_tbl (id bigint generated by default as identity, client_id bigint not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id));

DROP TABLE IF EXISTS transaction_tbl;
create table transaction_tbl (id bigint generated by default as identity, txn_account float(53) not null, txn_currency varchar(255) not null, txn_date timestamp(6), transaction_id bigint not null, txn_type varchar(255) not null, account_id bigint, primary key (id));

alter table if exists account_tbl add constraint FKh71j5x91326c23s1b0x94obl foreign key (client_id) references client_tbl;

alter table if exists transaction_tbl add constraint FKrqtejvh0yw8r17v2y42by80dq foreign key (account_id) references account_tbl;
